In [1]:
def multiplication(x,y):
    return x*y
    

In [2]:
multiplication(4,5)

20

In [9]:
def final_price(Price,Discount):
    return Price-(Discount*Price)
    

In [10]:
final_price(1000,0.25)

750.0

In [11]:
#an anonymous function, single expression

sq=lambda x:x*x

print(sq(5))

25


In [17]:
add=lambda x,y:x+y
add(3,7)

10

In [21]:
employees=[('Abdul',29),('Saddam',32),('Chandan',25),('Sravan',34),('Prateek',30),('Ajjin',28),('ashutosh',31)]
sorted_employee=sorted(employees,key=lambda x:x[1])

In [19]:
sorted_employee

[('Chandan', 25),
 ('Ajjin', 28),
 ('Abdul', 29),
 ('Prateek', 30),
 ('ashutosh', 31),
 ('Saddam', 32),
 ('Sravan', 34)]

In [25]:
def sort_by_age(employee):
    return employee[1]

In [26]:
employees=[('Abdul',29),('Saddam',32),('Chandan',25),('Sravan',34),('Prateek',30),('Ajjin',28),('ashutosh',31)]

In [29]:
sort_emp=sorted(employees,key=sort_by_age)
sort_emp

[('Chandan', 25),
 ('Ajjin', 28),
 ('Abdul', 29),
 ('Prateek', 30),
 ('ashutosh', 31),
 ('Saddam', 32),
 ('Sravan', 34)]

In [33]:
#map in lambda

#do the square of each no in a list

a=[1,2,3,4,5]

sq_a=list(map(lambda x:x*x,a))
sq_a

[1, 4, 9, 16, 25]

In [4]:
#reduce
from functools import reduce
a=[1,2,3,4,5,6,7]
prod=reduce(lambda x,y:x*y,a)

In [5]:
prod

5040

In [9]:
from functools import reduce
Fruits = ['apple', 'banana', 'watermelon', 'muskmelon', 'dragonfruit']
longest_string=reduce(lambda x,y: x if len(x) > len(y) else y,Fruits)

In [10]:
longest_string

'dragonfruit'

In [11]:
num=[1,2,3,4,5,6,7,8,9,10]
even_num=list(filter(lambda x:x%2==0,num))


In [12]:
even_num

[2, 4, 6, 8, 10]

In [16]:
Fruits = ['apple', 'banana', 'watermelon', 'muskmelon', 'dragonfruit']
n=6
more_than_six=list(filter(lambda x:len(x)>n,Fruits))

In [17]:
more_than_six

['watermelon', 'muskmelon', 'dragonfruit']

In [19]:
import numpy as np
arr=np.array([1,2,3,4,5])
type(arr)

array([1, 2, 3, 4, 5])

In [22]:
arr_2d=np.array([[1,2,3,4,5],[2,6,7,8,9],[8,9,6,7,3],[1,2,3,7,9]])
arr_2d

array([[1, 2, 3, 4, 5],
       [2, 6, 7, 8, 9],
       [8, 9, 6, 7, 3],
       [1, 2, 3, 7, 9]])

In [24]:
arr_2d[1:3,1:4]

array([[6, 7, 8],
       [9, 6, 7]])